name: Deploy Next.js App - Production
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-prod-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-prod-${{ hashFiles('**/package-lock.json') }}-

      - name: Build project
        run: npm run build

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Upload project files via rsync
        run: |
          rsync -avz --delete --exclude '.git' --exclude 'node_modules' \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/insightvision/

      - name: Deploy and run with PM2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ~/insightvision &&
            # Create a script to handle process management
            echo '#!/bin/bash
            
            # Function to find and kill process by port
            kill_port_process() {
                PORT=$1
                PID=$(sudo lsof -t -i:$PORT)
                if [ ! -z \"$PID\" ]; then
                    echo \"Killing process $PID using port $PORT\"
                    sudo kill -9 $PID
                fi
            }
            
            # Kill process using the specified port
            kill_port_process ${{ secrets.APP_PORT }}
            ' > manage_process.sh &&
            
            # Make the script executable
            chmod +x manage_process.sh &&
            
            # Run the process management script with sudo
            sudo ./manage_process.sh &&
            
            # Stop PM2 process if it exists
            pm2 delete insightvision || true &&
            
            # Install global dependencies with sudo
            sudo npm install -g pm2 next &&
            
            # Install project dependencies
            npm ci --omit=dev &&
            npm i sharp &&
            
            # Set proper ownership
            sudo chown -R $USER:$USER ~/insightvision &&
            
            # Start the application with PM2
            pm2 start npm --name 'insightvision' -- start -- --port ${{ secrets.APP_PORT }} &&
            pm2 save &&
            
            # Clean up
            rm manage_process.sh &&
            
            # Check if the app started successfully
            pm2 list | grep -q 'insightvision.*online' && echo 'App started successfully' || (pm2 logs insightvision --lines 50 && exit 1)
          "
